# SISTEMAS DE RECOMENDACIÓN

***

In [0]:
import numpy as np
import pandas as pd
import os
import sys

## Introduccion

Un sistema de recomendación(SR) proporciona sugerencias a usuarios sobre determinados elementos( **peliculas, libros** ) basado en sus interacciones en el sistema, con el fin de personalizar los gustos de cada usuario, dando a estos incentivo en seguir consumiendo otros productos.

Los SR tienen gran acogida desde pequeñas empresas(PYMES) a grandes empresas( ** Amazon, Netflix, Facebook, Linkedin ** ), una de las principales razones es el aumento de consumo de los productos en especifico en Amazon, Netflix por otro lado en el caso de Facebook y Linkedin, ofrecen ampliar las conexiones del usuario, asi fomenta las interacciones con dicha página.

<img src="https://raw.githubusercontent.com/Artcs1/Flisol2019_workshop/master/Imagenes/Fb_A_exam.png">

### Interacciones implicitas
Valoran si un item agrado al usuario basado en sus interacciones. Por ejemplo: La cantidad de tiempo que asististe un video (Youtube), que tipo de contenido estas viendo ( Netflix, Youtube) en caso veas peliculas de terror Netflix aumentaria tu nivel de coincidencia con este tipo de peliculas

#### Caracteristicas

* Son imprecisas
* No son intrusivas
* No piden informacion al usuario
* Promueven la comodidad del usuario

### Interacciones explicitas 
Piden informacion directamente al usuario. Por ejemplo: Si le gusto lo que acabar de ver/leer( Youtube : pulgar arriba/abajo) , rankear el producto de acuerdo a un escala ( PlayStore, Indriver : puntuar de 1 a 5 estrellas ) , pedir opiniones al usuario: ( Cambly, PlayStore)

#### Caracteristicas

* Son precisas
* Piden informacion al usuario
* Pueden ser intrusivas
* Puede resulta incomodo para el usuario


<img src="https://raw.githubusercontent.com/Artcs1/Flisol2019_workshop/master/Imagenes/matriz_representacion.png">

In [0]:
os.system("wget https://raw.githubusercontent.com/Artcs1/Flisol2019_workshop/master/Data/test_data.csv")
os.system("wget https://raw.githubusercontent.com/Artcs1/Flisol2019_workshop/master/Data/train_data%20.csv")
os.listdir()
test_data = pd.read_csv("test_data.csv")
train_data = pd.read_csv("train_data .csv")

In [5]:
os.listdir()

['.config', 'test_data.csv', 'train_data .csv', 'sample_data']

In [6]:
print(train_data)

        user_id  movie_id  rating  timestamp
0             1      1160       5  974769817
1             1      1129       3  974769817
2             1      3328       4  974769817
3             1      2659       2  974769817
4             1       980       3  974769817
5             1       561       4  974769790
6             1      1099       5  974769790
7             1      1112       5  974769790
8             1        32       3  974769790
9             1      2286       5  974769790
10            1      1067       5  974769764
11            1       821       4  974769764
12            1      1075       5  974769764
13            1       683       5  974769764
14            1      3116       4  974769764
15            1       249       5  974769764
16            1      1552       4  974769692
17            1      2677       2  974769669
18            1      1531       3  974769669
19            1       518       5  974769617
20            1      2226       4  974769434
21        

In [7]:
print(test_data)

        id  user_id  movie_id  timestamp
0        0        5      2962  974769784
1        1        5      3177  974769768
2        2        5      3153  974769768
3        3        5       501  974769768
4        4        5      3159  974769768
5        5        5      3176  974769768
6        6        5      3156  974769768
7        7        5      3193  974769737
8        8        5      2493  974769737
9        9        5      3097  974769737
10      10        9      1741  974769824
11      11        9      1117  974769824
12      12        9      2014  974769824
13      13        9      2178  974769824
14      14        9      3415  974769672
15      15        9      2310  974769672
16      16        9      1430  974769655
17      17        9      2404  974769655
18      18        9      2677  974769655
19      19        9      3420  974769655
20      20       11      1426  974769521
21      21       11      3195  974769330
22      22       11      3176  974769284
23      23      

In [8]:
Im = np.array([[1,1,5],[1,3,2],[2,2,2],[2,5,4.5],[3,1,4],[3,2,5],[3,3,1],[4,2,2.5],[4,3,3.5]])
print(Im)

[[1.  1.  5. ]
 [1.  3.  2. ]
 [2.  2.  2. ]
 [2.  5.  4.5]
 [3.  1.  4. ]
 [3.  2.  5. ]
 [3.  3.  1. ]
 [4.  2.  2.5]
 [4.  3.  3.5]]


In [9]:
matriz = np.zeros((5, 5))
for i in range(9):
    matriz[int(Im[i, 0] - 1), int(Im[i, 1] - 1)] = Im[i, 2]
    
print(matriz)

[[5.  0.  2.  0.  0. ]
 [0.  2.  0.  0.  4.5]
 [4.  5.  1.  0.  0. ]
 [0.  2.5 3.5 0.  0. ]
 [0.  0.  0.  0.  0. ]]


**Salida Esperada**:

<table class="egt">

  <tr>

    <td> </td>

    <td>Item 1 </td>

    <td>Item 2</td>
    
    <td>Item 3</td>
    
    <td>Item 4</td>
    
    <td>Item 5</td>

  </tr>

  <tr>

    <td>user 1</td>

    <td> 5 </td>

    <td> 0 </td>
    
    <td> 2</td>
    
    <td> 0</td>
    
    <td> 0</td>

  </tr>
  
  <tr>

    <td>user 2</td>

    <td> 0 </td>

    <td> 2 </td>
    
    <td> 0 </td>
    
    <td> 0 </td>
    
    <td> 4.5 </td>

  </tr>
  
  <tr>

    <td>user 3</td>

    <td> 4</td>

    <td> 5</td>
    
    <td> 1</td>
    
    <td> 0</td>
    
    <td> 0</td>

  </tr>
  
  <tr>

    <td>user 4</td>

    <td> 0</td>

    <td> 2.5</td>
    
    <td> 3.5</td>
    
    <td> 0</td>
    
    <td> 0</td>

  </tr>
  
  <tr>

    <td>user 5</td>

    <td> 0</td>

    <td> 2</td>
    
    <td> 0</td>
    
    <td> 3</td>
    
    <td> 0</td>

  </tr>

</table>

---

## Recomendacion Colaborativa

* Recomendacion basadas en opiniones elaboradas por otros usuarios( "Utiliza la sabiduria colectiva")
* Dos versiones: Basada Usuario a Usuario, Item a Item
* Limitacion "**Cold Start**", cuando se obtiene un nuevo usuario o un nuevo item

<img src = "https://raw.githubusercontent.com/Artcs1/Flisol2019_workshop/master/Imagenes/FC_ej_1.png" >

### Basado en Usuarios
Dado un usuario **u** y un item **i** aun no visto por **u**

**Algoritmo**

1. Encontrar un conjunto de usuarios que tengan preferencias parecidas com **u** y hayan evaluado **i**
2. Usar la media de sus evaluaciones para predecir el nivel de satisfacción de **u** por **i**
3. Hacer eso para todos los items que **u** aun no conoce, y recomiende los mejores 

<img src = "https://raw.githubusercontent.com/Artcs1/Flisol2019_workshop/master/Imagenes/FCusuarios_ej_1.png">

#### Similitud entre usuarios ( Correlacion de Pearson)
Dado
* $ u,v $ : Usuarios
* $ r_{u,i} $: Evaluacion del usuario **u** para un item **i**
* $ l_{u,v} $ : Conjunto de items evaluados por ambos u,v

$$ sim(u,v) = \frac{\sum _{i \in I_{uv}} (r_{ui} - \bar{r}_{u})(r_{vi}-\bar{r}_{v})}{\sqrt{\sum_{i \in I_{uv}}(r_{ui} - \bar{r}_{u})^{2}} \sqrt{\sum_{i \in I_{uv}}(r_{vi} - \bar{r}_{v} )^{2}}}$$

** Nota: ** Posibles valores entre -1 a +1

In [0]:
def sim_user_Pearson(user1, user2):
    T1 = np.where(np.isnan(user1),False,True)
    T2 = np.where(np.isnan(user2),False,True)
    TT = np.multiply(T1,T2)
    
    user1 = user1[TT]
    user2 = user2[TT]
    rmedia1 = np.mean(user1)
    rmedia2 = np.mean(user2)
    num = np.sum( np.multiply(user1- rmedia1, user2-rmedia2))
    den = np.multiply(np.sqrt(np.sum(np.power(user1 - rmedia1,2))),np.sqrt(np.sum(np.power(user2 - rmedia2,2))))
    return num/den;

In [11]:
Alice = np.array([5,3,4,4,float('nan')]) 
Bob   = np.array([3,1,2,3,3])
print(sim_user_Pearson(Alice,Bob))

0.8528028654224417


**Salida Esperada**:

<table>
    <tr>
        <td>
            ** Similaridad entre usuarios**
        </td>
        <td>
           0.85
        </td>
    </tr>

</table>

#### Predicción

$$ pred(u,i) = \bar{r_{u}} +\frac{\sum_{v \in U_{u}} sim(u,v)(r_{vi} - \bar{r}_{v})}{\sum_{v \in U_{u}} sim(u,v)} $$

In [0]:
def pred_user_Pearson(sim, userU, userV, mediaV):
    return np.nanmean(userU)+np.sum(np.multiply(sim,userV-mediaV))/np.sum(sim)

In [13]:

sims   = np.matrix([[0.85, 0.7]])
userV  = np.matrix([[3   , 5  ]])
mediaV = np.matrix([[2.4 , 3.8]])
print(pred_user_Pearson(sims, Alice, userV, mediaV))

4.870967741935484


**Salida Esperada**:

<table>
    <tr>
        <td>
            ** Predicción k =2 **
        </td>
        <td>
           4,87
        </td>
    </tr>

</table>

Donde $U_{u}$ son los k usuarios mas proximos

<img src = "https://raw.githubusercontent.com/Artcs1/Flisol2019_workshop/master/Imagenes/FCusuarios_ej_2.png">

In [14]:
def FC_usuarios(interacciones, Alice, Item): # Completar para el caso general

SyntaxError: ignored

### Basado en Items

Dado un usuario **u** y un item **i** aun no visto por **u**

**Algoritmo**

1. Encontrar un conjunto de items que tengan preferencias parecidas com **i** y hayan sido evaluados **u**
2. Usar la media de sus evaluaciones **u** de esos items para predecir el nivel de satisfacción de **u** por **i**
3. Hacer eso para todos los items que **u** aun no conoce, y recomiende los mejores 

#### Similitud entre items
Dado
* $ u,v $ : Usuarios
* $ r_{u,i} $: Evaluacion del usuario **u** para un item **i**
* $ U_{i,j} $ : Conjunto de usuarios que evaluaron i,j

$$ sim(u,v) = \frac{\sum _{i \in U_{ij}} (r_{ui} - \bar{r}_{u})(r_{uj}-\bar{r}_{u})}{\sqrt{\sum_{i \in I_{uv}}(r_{ui} - \bar{r}_{u})^{2}} \sqrt{\sum_{i \in I_{uv}}(r_{uj} - \bar{r}_{u} )^{2}}}$$

In [0]:
def sim_item_Pearson(item1, item2, mediaU):
    T1 = np.where(np.isnan(item1),False,True)
    T2 = np.where(np.isnan(item2),False,True)
    TT = np.multiply(T1,T2)
    
    Item1 = item1[TT]
    Item2 = item2[TT]
    mediaU = mediaU[TT]
    
    num = np.sum( np.multiply(Item1 - mediaU, Item2 - mediaU) )
    den = np.multiply(np.sqrt(np.sum(np.power(Item1 - mediaU,2))),np.sqrt(np.sum(np.power(Item2 - mediaU,2))))
    
    return num/den

In [16]:
item1 =  np.matrix([[3,5,4,1]])
item2 =  np.matrix([[3,3,5,2]])
mediaU = np.matrix([[2.4, 3.8, 3.2, 2.8]])
print(sim_item_Pearson(item1,item2,mediaU))

0.4330626889286792


**Salida Esperada**:

<table>
    <tr>
        <td>
            ** Similaridad entre items**
        </td>
        <td>
           0.43
        </td>
    </tr>

</table>

#### Predicción

$$ pred(u,i) =\frac{\sum_{v \in I_{u}} sim(i,j)r_{uj}}{\sum_{v \in I_{u}} sim(i,j)} $$

<img src ="https://raw.githubusercontent.com/Artcs1/Flisol2019_workshop/master/Imagenes/FCitems_ej_1.png">

In [0]:
def pred_item_Pearson(sim, Uij):
    return np.sum(np.multiply(sim,Uij))/np.sum(sim)

In [18]:
sim = np.matrix([[0.43, 0.80]])
Uij = np.matrix([[4 , 5]])
print(pred_item_Pearson(sim,Uij))

4.650406504065041


**Salida Esperada**:

<table>
    <tr>
        <td>
            ** Predicción k =2 **
        </td>
        <td>
           4,65
        </td>
    </tr>

</table>

In [19]:
def FC_items(interacciones, Alice, Item): # Completar para el caso general

SyntaxError: ignored

## Modelos Probabilísticos

### Idea Basica

* Dada una matriz de interacciones usuario - item, determinar la probabilidad en que un usuario $ u $ gustara de un item $ i $
* Realizar una recomendación con base en esas probabilidades
* El cálculo de las probabilidades es basado en el Teorema de Bayes

### Teorema Bayes

* ¿ Qúal es la probabilidad de que el $ Item5 $ ser visto  por $ Alice $ ?
* Probabilidad condicional: P( Item5 | X)

$$ P(Y|X) = \frac{P(X|Y)P(Y)}{P(X)}$$

$$ P(Y|X) = \frac{ \prod^{d}_{i=1}P(X_{i}|Y)P(Y)}{P(X)} $$

<img src="https://raw.githubusercontent.com/Artcs1/Flisol2019_workshop/master/Imagenes/Met_Prob.png" >

In [0]:
def NaiveBayes(PY, interacciones,userid,itemid):
    PXY = np.ones(5)
    item = interacciones[:,itemid]
    for i in np.arange(5):
        for j in np.arange(5):
            if np.isnan(interacciones[userid][j]) == False :
                Yi = np.where(item == i+1,1,0)
                Xi = np.where(interacciones[:,j] == interacciones[userid][j],1,0)
                Y = np.sum(Yi)
                X = np.sum(Xi*Yi)
                PXY[i] = PXY[i] * (X)/(Y+0.0000001)
    print(PXY)
    print(PXY*PY)
    return np.argmax(PXY*PY) + 1

In [21]:
I = np.array([[1,3,3,2,float('nan')],[2,4,2,2,4],[1,3,3,5,1],[4,5,2,3,3],[1,1,5,2,1]])
PY = np.array([0.5,0,0.25,0.25,0])
user = 0
item = 4
print(NaiveBayes(PY,I,user,item))

[0.12499998 0.         0.         0.         0.        ]
[0.06249999 0.         0.         0.         0.        ]
1


**Salida Esperada**:

<table>
    <tr>
        <td>
            ** Algoritmo Naive Bayes**
        </td>
        <td>
           1
        </td>
    </tr>

</table>

## Recomendación basada en Contenido

El contenido puede ser estructurado, semi-estructurado, no-estructurado. Los datos estructurados hacen referencias a informaciones del tipo(atributo, valor) y pueden ser extraidas facilmente, permite un intervalos para valores numericos exacto. Los datos no estructurados se refiere a texto libre, esto permite consultas basadas en **palabras clave**, consultas mas sofisticadas basadas en conceptos

<img src = "https://raw.githubusercontent.com/Artcs1/Flisol2019_workshop/master/Imagenes/FBC_ej_1.png">

### Procesamiento de palabras clave

<img src = "https://raw.githubusercontent.com/Artcs1/Flisol2019_workshop/master/Imagenes/FBC_ej_2.png">

#### Tokenizacion

#### Remover de stop words

#### Normalizacion de los terminos

#### Lematizacion

#### Radicalizacion

### Ponderacion TF-IDF

### Similaridad ( Modelo Vectorial)

* Contacto: ju.jeffri.v@gmail.com